// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Q_txDvxGf8msQ7jh0ZTy47vn0YA9Mbk',
    appId: '1:922580097838:web:9b4befaba8fd45e97e38bf',
    messagingSenderId: '922580097838',
    projectId: 'utm-let-go',
    authDomain: 'utm-let-go.firebaseapp.com',
    storageBucket: 'utm-let-go.appspot.com',
    measurementId: 'G-9KJN2R9HGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSZGz6upvtmrPpdsUfTvbSK9OFIRizNt4',
    appId: '1:922580097838:android:d42485338016b4307e38bf',
    messagingSenderId: '922580097838',
    projectId: 'utm-let-go',
    storageBucket: 'utm-let-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbQ7hcy9ehpvMwoctcL3JvNvL0YjUOCo',
    appId: '1:922580097838:ios:2a2f9a68403b05b37e38bf',
    messagingSenderId: '922580097838',
    projectId: 'utm-let-go',
    storageBucket: 'utm-let-go.appspot.com',
    androidClientId: '922580097838-hg73kmqn3nljehiip2ihimq1h23j5jbh.apps.googleusercontent.com',
    iosClientId: '922580097838-ug93v7fssdr8tc1oi27o8r0c0ss8he58.apps.googleusercontent.com',
    iosBundleId: 'com.example.utmletgo',
  );
}
